site_name: Lokal Docs
site_url: https://docs.lokal.network/
repo_name: Wakoma/docs
repo_url: https://github.com/Wakoma/docs
theme:
  icon:
    repo: fontawesome/brands/github
  name: 'material'
  logo: assets/wakomalogowhite.png
  favicon: assets/wakomalogo.png
  features:
    - navigation.instant
    - navigation.sections
extra_css:
  - css/extra.css
extra:
  homepage: https://wakoma.co/lokal/
nav:
  - Home: index.md
  - Getting Started: gettingstarted.md
  - Resources: resources.md
  - Services:
    - Current Services:
      - services/azuracast/azuracast.md
      - services/calibre_web/calibre_web.md
      - services/collabora/collabora.md
      - services/element/element.md
      - services/fdroid/fdroid.md
      - services/grafana/grafana.md
      - services/ipfs/ipfs.md
      - services/jellyfin/jellyfin.md
      - services/jitsi/jitsi.md
      - services/kiwix/kiwix.md
      - services/kolibri/kolibri.md
      - services/matomo/matomo.md
      - services/matrix/matrix.md
      - services/moodle/moodle.md
      - services/nextcloud/nextcloud.md
      - services/openvpn/openvpn.md
      - services/prometheus/prometheus.md
      - services/resourcespace/resourcespace.md
      - services/transmission/transmission.md
      - services/uisp/uisp.md
      - services/unifi_controller/unifi_controller.md
      - services/unpoller/unpoller.md
      - services/wireguard/wireguard.md
      - services/wordpress/wordpress.md
    - Upcoming Services:
      - services/archivebox/archivebox.md
      - services/librenms/librenms.md
      - services/mumble/mumble.md
      - services/netbox/netbox.md
      - services/openwisp/openwisp.md
      - services/snipeit/snipeit.md
      - services/zabbix/zabbix.md
      - services/zeek/zeek.md
      - services/bigbluebutton/bigbluebutton.md
      - services/diagrams_net/diagrams_net.md
      - services/discourse/discourse.md
      - services/dokuwiki/dokuwiki.md
      - services/etherpad/etherpad.md
      - services/hedgedoc/hedgedoc.md
      - services/homeassistant/homeassistant.md
      - services/limesurvey/limesurvey.md
      - services/lychee/lychee.md
      - services/mediawiki/mediawiki.md
      - services/minecraft/minecraft.md
      - services/osticket/osticket.md
      - services/piwigo/piwigo.md
      - services/roundcube/roundcube.md
      - services/syncthing/syncthing.md
      - services/tinytinyrss/tinytinyrss.md
