site_name: Lokal Docs
site_url: https://docs.lokal.network/
repo_name: Wakoma/docs
repo_url: https://github.com/Wakoma/docs
# copyright: Text goes here
theme:
  icon:
    repo: fontawesome/brands/github
  name: 'material'
  logo: assets/wakomalogowhite.png
  favicon: assets/wakomalogo.png
  features:
    - navigation.instant
    - navigation.sections
    - navitation.footer
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/extra.css
extra:
  homepage: https://wakoma.co/lokal/
  generator: false
  # social:
  #   - icon: 
  #     link: https://twitter.com/wakomainc
  #   - icon: fontawesome/brands/linkedin
  #     link: https://www.linkedin.com/company/18222794
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/Wakoma
nav:
  - Home: index.md
  - Getting Started: gettingstarted.md
  - Getting Advanced: advancedtopics.md
  - Resources: resources.md
  - Services:
    - Current Services:
      - Azuracast: services/azuracast/index.md
      - Calibre_web: services/calibre_web/index.md
      - Collabora: services/collabora/index.md
      - Element: services/element/index.md
      - Fdroid: services/fdroid/index.md
      - Grafana: services/grafana/index.md
      - Ipfs: services/ipfs/index.md
      - Jellyfin: services/jellyfin/index.md
      - Jitsi: services/jitsi/index.md
      - Kiwix: services/kiwix/index.md
      - Kolibri: services/kolibri/index.md
      - Matomo: services/matomo/index.md
      - Matrix: services/matrix/index.md
      - Moodle: services/moodle/index.md
      - Nextcloud: services/nextcloud/index.md
      - Openvpn: services/openvpn/index.md
      - Prometheus: services/prometheus/index.md
      - Resourcespace: services/resourcespace/index.md
      - Transmission: services/transmission/index.md
      - Uisp: services/uisp/index.md
      - Unifi_controller: services/unifi_controller/index.md
      - Unpoller: services/unpoller/index.md
      - Wireguard: services/wireguard/index.md
      - Wordpress: services/wordpress/index.md
    - Upcoming Services:
      - Archivebox: services/archivebox/index.md
      - Librenms: services/librenms/index.md
      - Mumble: services/mumble/index.md
      - Netbox: services/netbox/index.md
      - Openwisp: services/openwisp/index.md
      - Snipeit: services/snipeit/index.md
      - Zabbix: services/zabbix/index.md
      - Zeek: services/zeek/index.md
      - Bigbluebutton: services/bigbluebutton/index.md
      - Diagrams_net: services/diagrams_net/index.md
      - Discourse: services/discourse/index.md
      - Dokuwiki: services/dokuwiki/index.md
      - Etherpad: services/etherpad/index.md
      - Hedgedoc: services/hedgedoc/index.md
      - Homeassistant: services/homeassistant/index.md
      - Limesurvey: services/limesurvey/index.md
      - Lychee: services/lychee/index.md
      - Mediawiki: services/mediawiki/index.md
      - Minecraft: services/minecraft/index.md
      - Osticket: services/osticket/index.md
      - Piwigo: services/piwigo/index.md
      - Roundcube: services/roundcube/index.md
      - Syncthing: services/syncthing/index.md
      - Tinytinyrss: services/tinytinyrss/index.md
