site_name: Lokal Documentation
site_url: https://docs.lokal.network/
theme:
  name: 'material'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
     - navigation.sections
nav:
  - Home: index.md
  - About: about.md
  - Services: services.md
  - Installation : installation.md

