site_name: Lokal Documentation
site_url: https://docs.lokal.network/
theme:
  name: 'material'
  logo: assets/wakomalogo.png
  favicon: assets/wakomalogo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
nav:
  - Home: index.md
  - About: about.md
  - Services: services.md
  - Installation : installation.md
extra_css:
  - css/extra.css
  